# Generated by Django 2.2.4 on 2021-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_acceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupacion',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'Categoría1'), ('categoria2', 'Categoría2'), ('categoria3', 'Categoría3')], max_length=80),
        ),
    ]
