# Generated by Django 2.2.4 on 2021-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0002_auto_20210428_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='aporte',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
    ]
