# Generated by Django 2.2.4 on 2021-04-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0003_aporte_rechazado'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
