# Generated by Django 2.2.4 on 2021-04-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_acceso', '0002_auto_20210423_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupacion',
            name='categoria',
            field=models.CharField(choices=[('1', 'Animalista'), ('2', 'Adulto Mayor'), ('3', 'Situación de Calle')], max_length=80),
        ),
    ]
