# Generated by Django 2.2.4 on 2021-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_acceso', '0003_auto_20210428_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrupacion',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agrupacion',
            name='necesitamos',
            field=models.TextField(blank=True, max_length=750),
        ),
    ]
