# Generated by Django 2.2.4 on 2021-04-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_acceso', '0004_auto_20210428_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agrupacion',
            old_name='password',
            new_name='group_password',
        ),
    ]
