# Generated by Django 2.2.4 on 2021-05-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_acceso', '0005_auto_20210428_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agrupacion',
            old_name='group_password',
            new_name='password',
        ),
    ]
